"""Added Bank model

Revision ID: e52a8ad8911e
Revises: 6185647318ea
Create Date: 2023-09-07 10:51:39.384879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e52a8ad8911e'
down_revision = '6185647318ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
